### ISSUE TITLE
Success/Failure stdout output

### ISSUE THREAD

**Issue by TehPeGaSuS** [osm/icka#1]
Would be nice to be able to view the success/failure message, kind of like [here](https://github.com/vijaiaeroastro/irccloud).

This would allow us to automate stuff based on the output

**Comment by osm** [comment]
Hi,

You can use the exit code of the program to determine whether or not it was a successful or failed keep alive attempt. Any non zero exit code means that something failed and an error is printed to stderr.

You could do something like this in a shell script
```sh
#!/bin/sh

icka -email foo@example.com -password pass1234
if [ $? -eq 0 ]; then
        echo "success"
fi
```
