### ISSUE TITLE
[URGENT] Error: get auth token failed

### ISSUE THREAD

**Issue by TehPeGaSuS** [osm/icka#10]
@osm

So, recently I've tried to use `icka` and i got the following: 
```
$ ICKA_EMAIL="account_email" ICKA_PASSWORD="account_password" /home/icka/go/bin/icka 
get auth token failed
```

Could you fix this, please? I would if I knew how to! :grin: 

**NOTE:** Probably duplicate of #9

**Comment by opiqbox** [comment]
i got the same problem. maybe IRCcloud has change the code?

**Comment by osm** [comment]
They changed the auth formtoken URL, I've pushed a new commit to remedy the problem.

Ping @PeGaSuS-Coder @opiqbox @norrinr
