### ISSUE TITLE
Execution ends immediately

### ISSUE THREAD

**Issue by Luni-4** [osm/icka#3]
First of all, thanks for this tool! :smile: 

Unfortunately, when I try to run this tool locally, it ends immediately with exit code `0`.

I'm using this script to run it:

```bash
#!/bin/bash

export ICKA_EMAIL=my_email
export ICKA_PASSWORD=my_password
./icka
```
How can I run it indefinitely? Thanks in advance for your help!

**Comment by osm** [comment]
Hi,

That is the intended behaviour.

You should add it to cron and execute it once every hour, or if you prefer to use a shell script you can use something like this:

```sh
#!/bin/sh

export ICKA_EMAIL=my_email
export ICKA_PASSWORD=my_password

while [ 1 ]; do
      ./icka
      sleep 60m
done
```

**Comment by Luni-4** [comment]
I see, thanks for the info!

I was thinking to run that on `heroku`, now I need to discover how to do that with a `cron` job. I suppose I will use your script with a `worker` job though

Could you please add the example above, and an `heroku` example if it is possible, to the README?

**Comment by osm** [comment]
I see.

I don't really use heroku, but I've added a new command line flag that should be usable for you, fetch the latest source and use the -forever flag.

If you do, the program will keep running and execute once every hour.

**Comment by Luni-4** [comment]
Wow, this is great! Thanks a lot! :smile: 

Can I use that that option with the environment variables too? Because I can't see that in the environment variable example in the README. I suppose I can, but just to be sure

**Comment by tech234a** [comment]
I have a repo based on this script with easy, step-by-step setup instructions. It can be deployed to Heroku completely from a web browser without editing code, and it also uses far fewer Heroku account hours than running it forever.

https://github.com/tech234a/irccloud

For those of you who used this repo back when it was based on vijaiaeroastro's script: the easiest way to update is to delete your existing Heroku app, use the deploy button in the README to create a new app with the same name as your previous one, and make sure your existing cron-job.org job is enabled.
