### ISSUE TITLE
Easier step by step tutorial?

### ISSUE THREAD

**Issue by Cloud-user221** [osm/icka#7]
Hi there

Is there an easier step by step tutorial on how to achieve this, like the one Vijai had? Currently, looking at the code, cannot figure out how to implement this? Use own server or heroku, where to start from? How to create a bash script etc etc. I am sure there are many other who echo what I am saying. Many thanks.

**Comment by Deihmos** [comment]
You can use own server or heroku. I used heroku instead. You can follow the same instructions as Vijai and just edit the github link and password/email. Add a Procfile with this **worker: ./bin/icka -forever**

It runs every hour.

**Comment by Cloud-user221** [comment]
> You can use own server or heroku. I used heroku instead. You can follow the same instructions as Vijai and just edit the github link and password/email. Add a Procfile with this **worker: ./bin/icka -forever**
> 
> It runs every hour.

I am afraid Vijai has now removed his old article. Someone needs to make step by step instructions for those who are not that savvy with Linux command line, please. Thanks.

**Comment by kmikita** [comment]
$ git clone https://github.com/osm/icka.git
$ cd icka
$ heroku create
$ heroku config:set ICKA_EMAIL=your@email
$ heroku config:set ICKA_PASSWORD=your_password
$ echo "worker: ./bin/icka -forever" > Procfile
$ git add .
$ git commit -m "Procfile"
$ git push heroku master
$ heroku ps:scale worker=1
$ heroku logs

**Comment by Cloud-user221** [comment]
> $ git clone https://github.com/osm/icka.git
> $ cd icka
> $ heroku create
> $ heroku config:set ICKA_EMAIL=your@email
> $ heroku config:set ICKA_PASSWORD=your_password
> $ echo "worker: ./bin/icka -forever" > Procfile
> $ git add .
> $ git commit -m "Procfile"
> $ git push heroku master
> $ heroku ps:scale worker=1
> $ heroku logs

Thanks. Tried it on my Raspberry Pi and it failed at make stage. Tried git clone and it failed too. Any one willing to make a step by step guide?

**Comment by TehPeGaSuS** [comment]
The exact error output would be helpful though.

**Comment by Cloud-user221** [comment]
Thanks @PeGaSuS-Coder 

I managed to clone git and install Heroku on local server but now stuck at this stage:

pi@raspberrypi:~/icka $ git commit -m "Procfile"                                                                                                                                                                *** Please tell me who you are.                                                                                                                                                                                 Run                                                                                                                                                                                                               git config --global user.email "you@example.com"                                                        git config --global user.name "Your Name"                                                                                                                                                                     to set your account's default identity.                                                                 Omit --global to set the identity only in this repository.                                                                                                                                                      fatal: unable to auto-detect email address (got 'pi@raspberrypi.(none)')  

My question is, where do I enter my irccloud credentials? I haven't downloaded irccloud.git this time, like i did previously when following Vijae's instructions (server has changed since then and no longer has irccloud.git installed) --- I have managed to log into my heroku account via CLI after installing heroku.

Much appreciated and TIA.

**Comment by tech234a** [comment]
I have a repo based on this script with easy, step-by-step setup instructions. It can be deployed to Heroku completely from a web browser without editing code, and it also uses far fewer Heroku account hours than running it forever.

https://github.com/tech234a/irccloud

For those of you who used this repo back when it was based on vijaiaeroastro's script: the easiest way to update is to delete your existing Heroku app, use the deploy button in the README to create a new app with the same name as your previous one, and make sure your existing cron-job.org job is enabled.

**Comment by Deihmos** [comment]
Thanks for this. It works well.

**Comment by larakel1** [comment]
Helllo any help for install with the new update? i just deleted the old and followed the old steps but dont success, in logs 
2022-05-18T09:05:04.363734+00:00 app[worker.1]: 2022/05/18 09:05:04 keep alive error: get session failed, check email and password

Thanks in advance

**Comment by tech234a** [comment]
Did you make sure to set the environment variables in the new version and make sure that the values are spelled correctly? (Also note that the IRCCloud username should be an email address.)

**Comment by larakel1** [comment]
> Did you make sure to set the environment variables in the new version and make sure that the values are spelled correctly? (Also note that the IRCCloud username should be an email address.)

Finally i did you repository with 100% success thanks
